<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ taglib prefix="sd" uri="/struts-dojo-tags"%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link href="mystyle.css" rel="stylesheet" type="text/css">
<title>Timesheet Report</title>
</head>
<body style="height: auto; border: 1px groove black;" marginheight="5px">
<img src="<s:url value="/images/timesheet.png"/>" />
	<div><s:label name="heading" value="Timesheet status summary."></s:label></div>
	<div><s:label name="Date" value="Date : "></s:label>
	<s:date name="currentDate" format="dd/MM/yyyy" /></div>
	
	<div><s:label name="Employee" value="Reported generated by : "></s:label>
	<s:property value="employee_name"/>  </div>

	<div align="center">

		<!-- list of time sheet goes here -->
		<table class="hovertable">
			<thead>
				<tr>
					<th>Work Date</th>
					<th>Employee</th>
					<th>Approver</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				<s:iterator value="reports">
					<tr>
						<!-- <td><s:checkbox name="time" id="time" fieldValue="%{timesheet_id}"></s:checkbox></td> -->
						<td><s:property value="work_date" />
						</td>
						<td><s:property value="emp_name" />
						</td>
						<td><s:property value="approver" />
						</td>
						<td><s:property value="status" />
						</td>

					</tr>
					<br />
				</s:iterator>
			</tbody>
		</table>
	</div>

</body>
</html>